Fixed error message

diff --git a/k8s/oc_operator_wan/bin_sh/login_padogrid_pod b/k8s/oc_operator_wan/bin_sh/login_padogrid_pod
--- a/k8s/oc_operator_wan/bin_sh/login_padogrid_pod
+++ b/k8s/oc_operator_wan/bin_sh/login_padogrid_pod
@@ -11,7 +11,7 @@ NAME
    $EXECUTABLE - Login to the PadoGrid pod
 
 SYNOPSIS
-   $EXECUTABLE wan1|wan2 [paodgrid_pod_name] [-?]
+   $EXECUTABLE [paodgrid_pod_name] [-?]
 
 OPTIONS
    padogrid_pod_name
@@ -29,8 +29,7 @@ if [ "$POD_NAME" == "" ]; then
    POD_NAME="$(oc get pods |grep padogrid-1 | grep -v deploy | sed 's/ .*//')"
 fi
 if [ "$POD_NAME" == "" ]; then
-   echo  >&2 "ERROR: Kafka pod name required"
-   echo "Usage: ./$EXECUTABLE padogrid_pod_name"
+   echo  >&2 "ERROR: PadoGrid pod not found in this project. Please see the usage. Command aborted."
    exit 1
 fi
 
