Tidied up scripts

diff --git a/k8s/oc_wan/bin_sh/stop_padogrid b/k8s/oc_wan/bin_sh/stop_padogrid
--- a/k8s/oc_wan/bin_sh/stop_padogrid
+++ b/k8s/oc_wan/bin_sh/stop_padogrid
@@ -11,13 +11,17 @@ NAME
    $EXECUTABLE - Deletes PadoGrid deployment
 
 SYNOPSIS
-   $EXECUTABLE [-all] [-?]
+   $EXECUTABLE wan1|wan2 [-all] [-?]
 
 DESCRIPTION
    Deletes PadoGrid deployment pods. If '-all' is specified then it also deletes the persistent
    claim and the 'local-storage' storage class.
 
 OPTIONS
+   wan1|wan2
+             This option is required. 'wan1' deletes resources in the '$PROJECT_WAN1' project and 
+             'wan2' deletses resources in the '$PROJECT_WAN2' project.
+
    -all
              If specified then it also deletes the 'padogrid-pvc' persistent claim along with
              'local-storage'.
@@ -26,10 +30,22 @@ EOF
 exit
 fi
 
+WAN=$1
+if [ "$WAN" != "wan1" ] && [ "$WAN" != "wan2" ]; then
+   echo >&2 "ERROR: Invalid input: [$WAN]. Please enter wan1 or wan2."
+   exit 1
+fi
+
+if [ "$WAN" == "wan1" ]; then
+   NAMESPACE=$PROJECT_WAN1
+else
+   NAMESPACE=$PROJECT_WAN2
+fi
+
 echo "Deleting PadoGrid..."
 oc delete all -l app=padogrid
 if [ "$ALL" == "true" ]; then
    echo "Deleting PadoGrid pvc, pv, and local-storage..."
-   oc delete pvc padogrid-pvc
-   oc delete -f $APP_DIR/padogrid/pv-hostPath.yaml > /dev/null 2>&1
+   oc delete --namespace=$NAMESPACE pvc padogrid-pvc
+   oc delete --namespace=$NAMESPACE -f $APP_DIR/padogrid/pv-hostPath.yaml > /dev/null 2>&1
 fi
